### PR TITLE
Add documentation and showcase site

### PR DESCRIPTION
**Pull request by eschalkargans**
## `documentation`

I initialized a "Material for Mkdocs" documentation, similarly to the one used for the VICALOPS prototype

## `greencity-showcase`

`greencity-showcase`: An attempt to remake the static site using TypeScript/React/Next/Tailwind

For the static site, this is a first draft I would like to show to Pierre Sicard. I'd like to get eventually a pipeline in which pushing on a special production branch would automatically build and redeploy the static site. If you have any ideas or did something similar before I would be interested (I did not checked GitHub actions yet, and I think it is probably doable without, eg if the github repo is hosted on the server with hooks configured)

Screenshot of the homepage: 
image

### CODE REVIEW

**Comment by fcoulibaly** [comment]
I have acces to this conversation

**Comment by fcoulibaly** [comment]
Globally, I like. Just I like when the text is aligned (I am maniac ;) ) 

“urban reforestation from space” seems focused only on trees, while shrubs are included (+ grass). Can we update as “urban greening” as mentioned in EU directives? 

reside in urban areas 

Steve wrote “air pollution is attributed to 11.65%...” = > Sincerely, I guess this sentence is not well structured, no? 

I suggest “11.6% of deaths globally are attributed to air pollution, i.e., a total of 7 million premature deaths annually”. 

Section “city greening”, I suggest “urban greening” rather than “reforestation” 

Services  

Inventory – put in bold – “Accurate data on location, species, and structural characteristics are essential for quantifying their benefits, however reliable information on urban vegetation in private areas and domestic gardens is lacking”. ARGANS is alone to do this job. 

Costs – 500 and not 50 

Quantifying the effects on air quality - Remove - To quantify the benefits, we provide charts of Urban Heat Islands for the entire city and an estimate of thermal comfort (Universal Thermal Comfort Index). 

Costs – 5000€ + inventory 

Create a new service “Urban Heat Island mapping” – A hybrid method to detect, classify, and map the Urban heat island is proposed with a classification based on the concept Local Climate Zones which is associated with automatic processing of satellite images Landsat-8 to define surface air temperature and sensitive areas.  

This service is billed at € 300 excluding tax per square kilometer of area analyzed. 

Assessment of health and socio-economic benefits – costs is 5000 (not 2500) 

Plus value – change 20% with 15% (the trees in private areas amount to about 85% of the trees’ population in cities)

**Comment by eschalkargans** [comment]
Hi,

Thanks for your feedback!

### 1

> Just I like when the text is aligned (I am maniac ;) )

Text justified (aligned) ✔️ 

| **Before** | **After** |
| - | - |
| image | image | 

### 2

> “urban reforestation from space”

Steve made the logo ; I will ask him for help

### 3
> I suggest “11.6% of deaths globally are attributed to air pollution, i.e., a total of 7 million premature deaths annually

Changed ✔️ 

### 4

> Section “city greening”, I suggest “urban greening” rather than “reforestation”

"Reforestation" word replaced by "greening" ✔️ 

### 5 
> Inventory – put in bold – “Accurate data on location, species, and structural characteristics are essential for quantifying their benefits, however reliable information on urban vegetation in private areas and domestic gardens is lacking”. ARGANS is alone to do this job.

- Price updated ✔️ 
- I appended the new sentence in bold at the end of the current text. Do you validate? ❓ 

| **Before** | **After** |
| - | -  |
| image |  image |

### 6 

> Quantifying the effects on air quality 

- Removed the sentence ✔️ 
- Regarding the cost: I wrote: `This service is billed at € 5,000 excluding tax + cost of the inventory`. However, I feel that this sentence is not well-worded. Can you provide to me the exact sentence you would like to have? Also, from my understanding, the `🌳 Quantifying the effects of green Spaces on air quality` service is dependent from the Inventory service. Maybe there is a better way to visually represent the package of services provided. We can discuss it. ❓ 

### 7

> Urban Heat Island mapping

Done ✔️ 
image


### 8

> Assessment of health and socio-economic benefits – costs is 5000 (not 2500)

Done ✔️ 

### 9

> Plus value

Done ✔️

**Comment by archonsme** [comment]
Hi Etienne

I use a MacOS proprietary software called Graphics, which used to be iDraw. I suspect it is an Inkscape clone with a MacOS interface, but the file format is .idraw, and I have not found other tools to open it.

Attached or a SVG and PNG of the logo with Reforestation changed to Greening.

Kind Regards
Steve

--
Dr Steve Emsley
Engineer

ARGANS

From: eschalkargans ***@***.***>
Date: Monday, 27 February 2023 at 10:38
To: ARGANS/greencity.argans.eu ***@***.***>
Cc: Stephen Emsley ***@***.***>, Mention ***@***.***>
Subject: Re: [ARGANS/greencity.argans.eu] Add documentation and showcase site (PR #1)

Hi Steve ( @archonsme<https://url6.mailanyone.net/scanner?m=1pWatR-0006yx-3H&d=4%7Cmail%2F90%2F1677493800%2F1pWatR-0006yx-3H%7Cin6n%7C57e1b682%7C25651682%7C11762917%7C63FC880D4326B9580A4525F045244335&o=%2Fphti%3A%2Fgtsmbthaco%2Fu.emsnohcr&s=oA09auM8U8IG-dvGUdu5qatBF4A> )

Do you think it is possible to update the Green City stamp logo? Or explain me how you created it so I can maybe update it myself? Thanks!

The requested change is the following: Urban Reforestation From Space -> Urban Greening From Space

Thanks!

**Pull request merged**
